// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quantum.Domain.Configuration;

#nullable disable

namespace Quantum.Domain.Migrations
{
    [DbContext(typeof(ModelDbContext))]
    [Migration("20230716101937_DbSchema")]
    partial class DbSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Quantum.Domain.Entities.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CONTENT");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ORDER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("PARENT_ID");

                    b.Property<string>("TYPE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("NODES");

                    b.HasDiscriminator<string>("TYPE").HasValue("Node");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Quantum.Domain.Entities.Nodes.Description", b =>
                {
                    b.HasBaseType("Quantum.Domain.Entities.Node");

                    b.ToTable("NODES");

                    b.HasDiscriminator().HasValue("DESCRIPTION");
                });

            modelBuilder.Entity("Quantum.Domain.Entities.Nodes.Image", b =>
                {
                    b.HasBaseType("Quantum.Domain.Entities.Node");

                    b.ToTable("NODES");

                    b.HasDiscriminator().HasValue("IMAGE");
                });

            modelBuilder.Entity("Quantum.Domain.Entities.Nodes.Page", b =>
                {
                    b.HasBaseType("Quantum.Domain.Entities.Node");

                    b.ToTable("NODES");

                    b.HasDiscriminator().HasValue("PAGE");
                });

            modelBuilder.Entity("Quantum.Domain.Entities.Nodes.Section", b =>
                {
                    b.HasBaseType("Quantum.Domain.Entities.Node");

                    b.ToTable("NODES");

                    b.HasDiscriminator().HasValue("Section");
                });

            modelBuilder.Entity("Quantum.Domain.Entities.Nodes.Sections.Heading", b =>
                {
                    b.HasBaseType("Quantum.Domain.Entities.Nodes.Section");

                    b.ToTable("NODES");

                    b.HasDiscriminator().HasValue("HEADING");
                });

            modelBuilder.Entity("Quantum.Domain.Entities.Nodes.Sections.Paragraph", b =>
                {
                    b.HasBaseType("Quantum.Domain.Entities.Nodes.Section");

                    b.ToTable("NODES");

                    b.HasDiscriminator().HasValue("PARAGRAPH");
                });

            modelBuilder.Entity("Quantum.Domain.Entities.Node", b =>
                {
                    b.HasOne("Quantum.Domain.Entities.Node", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Quantum.Domain.Entities.Node", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
